language: scala
scala:
  - 2.13.0
  - 2.12.6
  - 2.11.12
jdk:
  - openjdk8
  - openjdk11
script:
  - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
notifications:
  webhooks:
    urls:
      - https://nulab-inc.com/hubot/travis?room=3741
    on_success: change
